"""Script 04: Generate feasibility report.

Usage: python -m scripts.04_feasibility_report
"""

import sys
from datetime import datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from src.config import (
    P0_FIELDS, P1_FIELDS, P2_FIELDS,
    GO_THRESHOLD, CONDITIONAL_THRESHOLD, REPORTS_DIR,
)
from src.db import init_db, get_verdicts, get_scrape_stats
from src.analysis.feasibility import generate_report_data


def main():
    init_db()
    verdicts = get_verdicts()

    if not verdicts:
        print("No verdicts in database. Run scripts 02 and 03 first.")
        return 1

    data = generate_report_data(verdicts)
    scrape_stats = get_scrape_stats()

    # Generate markdown report
    report = f"""# KorupsiNLP — Feasibility Report
**Generated**: {datetime.now().strftime('%Y-%m-%d %H:%M')}
**Phase**: 0 (Feasibility Study)

---

## 1. Scraping Results

| Metric | Value |
|--------|-------|
| Total attempted | {scrape_stats.get('total', 'N/A')} |
| Successful | {scrape_stats.get('successes', 'N/A')} |
| Failed | {scrape_stats.get('failures', 'N/A')} |
| HTTP success rate | {scrape_stats['successes']/scrape_stats['total']*100:.1f}% |

## 2. Per-Field Parse Success Rates

### P0 Fields (Critical — required for core analysis)
| Field | Success Rate | Count |
|-------|-------------|-------|
"""

    rates = data["field_success_rates"]
    total = data["total_verdicts"]

    for f in P0_FIELDS:
        r = rates.get(f, 0)
        count = int(r * total)
        status = "GO" if r >= GO_THRESHOLD else "CONDITIONAL" if r >= CONDITIONAL_THRESHOLD else "NO-GO"
        report += f"| {f} | {r:.1%} ({count}/{total}) | {status} |\n"

    report += f"""
### P1 Fields (Important)
| Field | Success Rate | Count |
|-------|-------------|-------|
"""
    for f in P1_FIELDS:
        r = rates.get(f, 0)
        count = int(r * total)
        report += f"| {f} | {r:.1%} ({count}/{total}) |\n"

    report += f"""
### P2 Fields (Nice-to-have)
| Field | Success Rate | Count |
|-------|-------------|-------|
"""
    for f in P2_FIELDS:
        r = rates.get(f, 0)
        count = int(r * total)
        report += f"| {f} | {r:.1%} ({count}/{total}) |\n"

    report += f"""
## 3. Cross-Field Coverage

- **Full P0 coverage** (all 4 fields): {data['p0_coverage']:.1%} of verdicts

## 4. Format Analysis

| Format | Count | Rate |
|--------|-------|------|
| Has HTML text | {data['format_stats'].get('has_html_text', 0)} | {data['format_stats'].get('html_text_rate', 0):.1%} |
| Has PDF | {data['format_stats'].get('has_pdf', 0)} | {data['format_stats'].get('pdf_rate', 0):.1%} |
| Scanned PDF (no text) | {data['format_stats'].get('is_scanned', 0)} | {data['format_stats'].get('scanned_rate', 0):.1%} |

## 5. Scaling Estimate

Based on sample of {total} verdicts:
- Estimated total tipikor verdicts at MA level: ~3,639+
- Estimated scrape time (2s delay): ~{3639 * 2 / 3600:.1f} hours for listing + detail
- Storage estimate: ~{total * 0.5:.0f} KB per verdict HTML → ~{3639 * 0.5 / 1024:.1f} MB total

## 6. GO/NO-GO Decision

### **{data['decision']}**

{data['explanation']}

### Thresholds
- **GO**: ≥{GO_THRESHOLD:.0%} average P0 success rate
- **CONDITIONAL GO**: {CONDITIONAL_THRESHOLD:.0%}–{GO_THRESHOLD:.0%}
- **NO-GO**: <{CONDITIONAL_THRESHOLD:.0%}

---

*Report generated by KorupsiNLP Fase 0 feasibility pipeline.*
"""

    # Save report
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    report_path = REPORTS_DIR / "feasibility_report.md"
    report_path.write_text(report, encoding="utf-8")
    print(f"Report saved to: {report_path}")
    print(f"\nDecision: {data['decision']}")
    print(data['explanation'])

    return 0


if __name__ == "__main__":
    sys.exit(main())
